-- MySQL Script generated by MySQL Workbench
-- Mon Jul  6 19:39:42 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SIDEC
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `SIDEC` ;

-- -----------------------------------------------------
-- Schema SIDEC
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SIDEC` ;
USE `SIDEC` ;

-- -----------------------------------------------------
-- Table `SIDEC`.`ESTUDIANTE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SIDEC`.`ESTUDIANTE` ;

CREATE TABLE IF NOT EXISTS `SIDEC`.`ESTUDIANTE` (
  `Matricula` VARCHAR(15) NOT NULL,
  `Curp` VARCHAR(18) NOT NULL,
  `Nombre` VARCHAR(30) NOT NULL,
  `Apellido1` VARCHAR(15) NOT NULL,
  `Apellido2` VARCHAR(15) NULL DEFAULT NULL,
  `FechaNacimiento` DATE NOT NULL,
  `Telefono` VARCHAR(20) NULL DEFAULT NULL,
  `Correo` VARCHAR(30) NULL DEFAULT NULL,
  `Genero` VARCHAR(10) NOT NULL DEFAULT 'Masculino',
  `CicloEscolar` VARCHAR(10) NOT NULL,
  `NivelActual` VARCHAR(15) NOT NULL DEFAULT 'Primaria',
  `Status` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`Matricula`),
  UNIQUE INDEX `UNIQUE_Curp` (`Curp` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SIDEC`.`TUTOR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SIDEC`.`TUTOR` ;

CREATE TABLE IF NOT EXISTS `SIDEC`.`TUTOR` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(30) NOT NULL,
  `Apellido1` VARCHAR(15) NOT NULL,
  `Apellido2` VARCHAR(15) NULL DEFAULT NULL,
  `TelefonoPersonal` VARCHAR(20) NOT NULL,
  `TelefonoTrabajo` VARCHAR(20) NULL DEFAULT NULL,
  `Correo` VARCHAR(30) NULL DEFAULT NULL,
  `Genero` VARCHAR(10) NOT NULL DEFAULT 'Masculino',
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SIDEC`.`DOMICILIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SIDEC`.`DOMICILIO` ;

CREATE TABLE IF NOT EXISTS `SIDEC`.`DOMICILIO` (
  `MatEstudiante` VARCHAR(15) NOT NULL,
  `IdTutor` INT NOT NULL,
  `Calle` VARCHAR(30) NOT NULL,
  `NoExterior` VARCHAR(5) NOT NULL,
  `NoInterior` VARCHAR(5) NULL DEFAULT 'S/N',
  `Colonia` VARCHAR(30) NOT NULL,
  `Municipio` VARCHAR(30) NOT NULL,
  `CodigoPostal` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`IdTutor`, `MatEstudiante`),
  INDEX `FK_EST_idx` (`MatEstudiante` ASC),
  CONSTRAINT `FK_EST_DOM`
    FOREIGN KEY (`MatEstudiante`)
    REFERENCES `SIDEC`.`ESTUDIANTE` (`Matricula`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_TUT_DOM`
    FOREIGN KEY (`IdTutor`)
    REFERENCES `SIDEC`.`TUTOR` (`Id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SIDEC`.`CONDUCTA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SIDEC`.`CONDUCTA` ;

CREATE TABLE IF NOT EXISTS `SIDEC`.`CONDUCTA` (
  `MatEstudiante` VARCHAR(15) NOT NULL,
  `Fecha` DATETIME NOT NULL,
  `Observaciones` TEXT NOT NULL,
  PRIMARY KEY (`MatEstudiante`, `Fecha`),
  CONSTRAINT `FK_EST_CON`
    FOREIGN KEY (`MatEstudiante`)
    REFERENCES `SIDEC`.`ESTUDIANTE` (`Matricula`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SIDEC`.`USUARIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SIDEC`.`USUARIO` ;

CREATE TABLE IF NOT EXISTS `SIDEC`.`USUARIO` (
  `CCT` VARCHAR(15) NOT NULL,
  `Password` VARCHAR(255) NOT NULL,
  `Correo` VARCHAR(30) NULL DEFAULT NULL,
  `Nombre` VARCHAR(30) NOT NULL,
  `Apellido1` VARCHAR(15) NOT NULL,
  `Apellido2` VARCHAR(15) NULL DEFAULT NULL,
  `Rol` VARCHAR(15) NOT NULL DEFAULT 'Docente',
  PRIMARY KEY (`CCT`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SIDEC`.`REPORTE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SIDEC`.`REPORTE` ;

CREATE TABLE IF NOT EXISTS `SIDEC`.`REPORTE` (
  `Folio` INT NOT NULL AUTO_INCREMENT,
  `Fecha` DATETIME NOT NULL,
  `Motivo` VARCHAR(30) NOT NULL,
  `Descripcion` TEXT NOT NULL,
  `Canalizacion` TEXT NOT NULL,
  `CCT` VARCHAR(15) NOT NULL,
  `MatEstudiante` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`Folio`, `MatEstudiante`, `CCT`),
  INDEX `FK_USU_REP_idx` (`CCT` ASC),
  INDEX `FK_EST_REP_idx` (`MatEstudiante` ASC),
  CONSTRAINT `FK_USU_REP`
    FOREIGN KEY (`CCT`)
    REFERENCES `SIDEC`.`USUARIO` (`CCT`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_EST_REP`
    FOREIGN KEY (`MatEstudiante`)
    REFERENCES `SIDEC`.`ESTUDIANTE` (`Matricula`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SIDEC`.`INFORMACION_CLINICA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SIDEC`.`INFORMACION_CLINICA` ;

CREATE TABLE IF NOT EXISTS `SIDEC`.`INFORMACION_CLINICA` (
  `MatEstudiante` VARCHAR(15) NOT NULL,
  `Peso` DECIMAL(5,2) NOT NULL,
  `Estatura` DECIMAL(5,2) NOT NULL,
  `Imc` DECIMAL(5,2) NOT NULL,
  `TipoSangre` VARCHAR(5) NOT NULL DEFAULT 'O+',
  `NumeroSeguro` VARCHAR(20) NOT NULL,
  `UnidadMedica` VARCHAR(10) NOT NULL,
  `Alergias` TEXT NULL DEFAULT NULL,
  `EnferCronicas` TEXT NULL DEFAULT NULL,
  `EnferHereditarias` TEXT NULL DEFAULT NULL,
  `Discapacidades` TEXT NULL DEFAULT NULL,
  `DiagPsico` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`MatEstudiante`),
  CONSTRAINT `FK_ESTUDIANTES_INFORMACION_CLINICA`
    FOREIGN KEY (`MatEstudiante`)
    REFERENCES `SIDEC`.`ESTUDIANTE` (`Matricula`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SIDEC`.`LOGRO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SIDEC`.`LOGRO` ;

CREATE TABLE IF NOT EXISTS `SIDEC`.`LOGRO` (
  `Folio` INT NOT NULL AUTO_INCREMENT,
  `MatEstudiante` VARCHAR(15) NOT NULL,
  `Tipo` VARCHAR(20) NOT NULL,
  `Descripcion` TEXT NOT NULL,
  `Fecha` DATE NOT NULL,
  PRIMARY KEY (`Folio`),
  INDEX `fk_LOG_EST_idx` (`MatEstudiante` ASC),
  CONSTRAINT `fk_LOG_EST`
    FOREIGN KEY (`MatEstudiante`)
    REFERENCES `SIDEC`.`ESTUDIANTE` (`Matricula`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
